[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F767ZI"

rustflags = [
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7m-none-eabi"    # Cortex-M3

[env]
DEFMT_LOG = "info"
CHIPSERIE = "stm32f746"
